// Code generated by protoc-gen-go.
// source: exchange_rate.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	exchange_rate.proto
	service.proto

It has these top-level messages:
	ExchangeRateEntities
	ExchangeRateEntity
	ExchangeRateGetRateRequest
	ExchangeRateGetRateResponse
	ExchangeRateConvertRequest
	ExchangeRateConvertResponse
	StatusRequest
	StatusResponse
	PingRequest
	PingResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExchangeRateEntities struct {
	Results []*ExchangeRateEntity `protobuf:"bytes,1,rep,name=Results,json=results" json:"Results,omitempty"`
}

func (m *ExchangeRateEntities) Reset()                    { *m = ExchangeRateEntities{} }
func (m *ExchangeRateEntities) String() string            { return proto.CompactTextString(m) }
func (*ExchangeRateEntities) ProtoMessage()               {}
func (*ExchangeRateEntities) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ExchangeRateEntities) GetResults() []*ExchangeRateEntity {
	if m != nil {
		return m.Results
	}
	return nil
}

type ExchangeRateEntity struct {
	Id           int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CurrencyCode string  `protobuf:"bytes,2,opt,name=currency_code,json=currencyCode" json:"currency_code,omitempty"`
	Rate         float32 `protobuf:"fixed32,3,opt,name=rate" json:"rate,omitempty"`
	Date         string  `protobuf:"bytes,4,opt,name=date" json:"date,omitempty"`
	Created      string  `protobuf:"bytes,5,opt,name=created" json:"created,omitempty"`
	Modified     string  `protobuf:"bytes,6,opt,name=modified" json:"modified,omitempty"`
}

func (m *ExchangeRateEntity) Reset()                    { *m = ExchangeRateEntity{} }
func (m *ExchangeRateEntity) String() string            { return proto.CompactTextString(m) }
func (*ExchangeRateEntity) ProtoMessage()               {}
func (*ExchangeRateEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

//
type ExchangeRateGetRateRequest struct {
	// / Input currency type
	// / Must be ISO 4217 3 letter currency code
	FromCurrency string `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency" json:"from_currency,omitempty"`
	// / Output currency type
	// / Must be ISO 4217 3 letter currency code
	ToCurrency string `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency" json:"to_currency,omitempty"`
	// / The date on which to sample the exchange rate
	// / YYYY-MM-DD format
	Date string `protobuf:"bytes,3,opt,name=date" json:"date,omitempty"`
}

func (m *ExchangeRateGetRateRequest) Reset()                    { *m = ExchangeRateGetRateRequest{} }
func (m *ExchangeRateGetRateRequest) String() string            { return proto.CompactTextString(m) }
func (*ExchangeRateGetRateRequest) ProtoMessage()               {}
func (*ExchangeRateGetRateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ExchangeRateGetRateResponse struct {
	// / Same value as in ExchangeRateGetRateRequest
	FromCurrency string `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency" json:"from_currency,omitempty"`
	// / Same value as in ExchangeRateGetRateRequest
	ToCurrency string `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency" json:"to_currency,omitempty"`
	// / Same value as in ExchangeRateGetRateRequest
	Date string `protobuf:"bytes,3,opt,name=date" json:"date,omitempty"`
	// / Currency exchange rate response from request
	Rate float32 `protobuf:"fixed32,4,opt,name=rate" json:"rate,omitempty"`
}

func (m *ExchangeRateGetRateResponse) Reset()                    { *m = ExchangeRateGetRateResponse{} }
func (m *ExchangeRateGetRateResponse) String() string            { return proto.CompactTextString(m) }
func (*ExchangeRateGetRateResponse) ProtoMessage()               {}
func (*ExchangeRateGetRateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ExchangeRateConvertRequest struct {
	FromCurrency string  `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency" json:"from_currency,omitempty"`
	ToCurrency   string  `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency" json:"to_currency,omitempty"`
	Date         string  `protobuf:"bytes,3,opt,name=date" json:"date,omitempty"`
	Rate         float32 `protobuf:"fixed32,4,opt,name=rate" json:"rate,omitempty"`
	Amount       float32 `protobuf:"fixed32,5,opt,name=amount" json:"amount,omitempty"`
}

func (m *ExchangeRateConvertRequest) Reset()                    { *m = ExchangeRateConvertRequest{} }
func (m *ExchangeRateConvertRequest) String() string            { return proto.CompactTextString(m) }
func (*ExchangeRateConvertRequest) ProtoMessage()               {}
func (*ExchangeRateConvertRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ExchangeRateConvertResponse struct {
	FromCurrency string  `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency" json:"from_currency,omitempty"`
	ToCurrency   string  `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency" json:"to_currency,omitempty"`
	Date         string  `protobuf:"bytes,3,opt,name=date" json:"date,omitempty"`
	Rate         float32 `protobuf:"fixed32,4,opt,name=rate" json:"rate,omitempty"`
	Amount       float32 `protobuf:"fixed32,5,opt,name=amount" json:"amount,omitempty"`
	Result       float32 `protobuf:"fixed32,6,opt,name=result" json:"result,omitempty"`
}

func (m *ExchangeRateConvertResponse) Reset()                    { *m = ExchangeRateConvertResponse{} }
func (m *ExchangeRateConvertResponse) String() string            { return proto.CompactTextString(m) }
func (*ExchangeRateConvertResponse) ProtoMessage()               {}
func (*ExchangeRateConvertResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*ExchangeRateEntities)(nil), "pb.ExchangeRateEntities")
	proto.RegisterType((*ExchangeRateEntity)(nil), "pb.ExchangeRateEntity")
	proto.RegisterType((*ExchangeRateGetRateRequest)(nil), "pb.ExchangeRateGetRateRequest")
	proto.RegisterType((*ExchangeRateGetRateResponse)(nil), "pb.ExchangeRateGetRateResponse")
	proto.RegisterType((*ExchangeRateConvertRequest)(nil), "pb.ExchangeRateConvertRequest")
	proto.RegisterType((*ExchangeRateConvertResponse)(nil), "pb.ExchangeRateConvertResponse")
}

func init() { proto.RegisterFile("exchange_rate.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x93, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0xa4, 0xb4, 0x30, 0x05, 0x16, 0x06, 0x55, 0x51, 0x59, 0x80, 0xcc, 0xa6, 0xab,
	0x0a, 0xc1, 0x11, 0xaa, 0x0a, 0xd6, 0xbe, 0x40, 0x94, 0x9f, 0x29, 0x44, 0x22, 0x76, 0xb0, 0x9d,
	0x8a, 0x9e, 0x81, 0x5b, 0xb0, 0xe1, 0x10, 0x5c, 0x0e, 0xdb, 0xf9, 0x03, 0x5a, 0x96, 0x15, 0xab,
	0xce, 0xbc, 0xf7, 0x54, 0x7f, 0x79, 0x89, 0xe1, 0x0c, 0x5f, 0xd3, 0xa7, 0x98, 0x3f, 0x62, 0x24,
	0x63, 0x8d, 0xf3, 0x52, 0x0a, 0x2d, 0x88, 0x5f, 0x26, 0xf4, 0x01, 0xce, 0x97, 0x8d, 0xc5, 0x8c,
	0xb3, 0xe4, 0x3a, 0xd7, 0x39, 0x2a, 0x72, 0x03, 0x23, 0x86, 0xaa, 0x7a, 0xd6, 0x2a, 0xf4, 0xae,
	0x82, 0xd9, 0xf8, 0x76, 0x32, 0x2f, 0x93, 0xf9, 0x56, 0x74, 0xc3, 0x46, 0xb2, 0x8e, 0xd1, 0x0f,
	0x0f, 0xc8, 0xb6, 0x4f, 0x4e, 0xc1, 0xcf, 0x33, 0xf3, 0x1f, 0xde, 0x2c, 0x60, 0x66, 0x22, 0xd7,
	0x70, 0x92, 0x56, 0x52, 0x22, 0x4f, 0x37, 0x51, 0x2a, 0x32, 0x0c, 0x7d, 0x63, 0x1d, 0xb1, 0xe3,
	0x56, 0x5c, 0x18, 0x8d, 0x10, 0x18, 0x58, 0xce, 0x30, 0x30, 0x9e, 0xcf, 0xdc, 0x6c, 0xb5, 0xcc,
	0x6a, 0x03, 0x97, 0x77, 0x33, 0x09, 0x61, 0x94, 0x4a, 0x34, 0x53, 0x16, 0x1e, 0x38, 0xb9, 0x5d,
	0xc9, 0x14, 0x0e, 0x0b, 0x91, 0xe5, 0xab, 0xdc, 0x58, 0x43, 0x67, 0x75, 0x3b, 0x5d, 0xc3, 0xf4,
	0x3b, 0xe8, 0x3d, 0x6a, 0xfb, 0xc3, 0xf0, 0xa5, 0x42, 0xa5, 0x2d, 0xe0, 0x4a, 0x8a, 0x22, 0x6a,
	0x81, 0x1c, 0xbb, 0x01, 0xb4, 0xe2, 0xa2, 0xd1, 0xc8, 0x25, 0x8c, 0xb5, 0xe8, 0x23, 0xf5, 0x33,
	0x80, 0x16, 0x5d, 0xa0, 0xa5, 0x0d, 0x7a, 0x5a, 0xfa, 0xe6, 0xc1, 0xc5, 0xce, 0x83, 0x55, 0x29,
	0xb8, 0xc2, 0xfd, 0x9d, 0xdc, 0xf5, 0x39, 0xe8, 0xfb, 0xa4, 0xef, 0xde, 0xcf, 0x1a, 0x16, 0x82,
	0xaf, 0x51, 0xea, 0xbd, 0xd7, 0xb0, 0x0b, 0x86, 0x4c, 0x60, 0x18, 0x17, 0xa2, 0xe2, 0xda, 0xbd,
	0x47, 0x9f, 0x35, 0x1b, 0xfd, 0xfc, 0x55, 0x59, 0x07, 0xf9, 0x1f, 0x95, 0xfd, 0x45, 0x69, 0xf5,
	0xfa, 0x16, 0xb8, 0x4f, 0xcd, 0xe8, 0xf5, 0x96, 0x0c, 0xdd, 0x3d, 0xbb, 0xfb, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x36, 0x57, 0x9a, 0x11, 0x7e, 0x03, 0x00, 0x00,
}
